### ISSUE TITLE
Add ability to apply additional configuration options to the cloudflared instance

### ISSUE THREAD

**Issue by TroyKomodo** [pl4nty/cloudflare-kubernetes-gateway#161]
Allow for specifying replicas, affinity, tolerations on the cloudflared deployments.

And potentially create a service and or service monitors for metrics.

**Comment by pl4nty** [comment]
It should already be possible to create your own cloudflared deployments, since the operator uses the Cloudflare API for routing, rather than a local config file. If that works for you, I can add a [GatewayInfrastructure](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayInfrastructure) parameter to disable the operator's deployment.

Tunnel metrics are available on port 2000, but controller metrics aren't enabled. I'll fix that in the next release and add optional ServiceMonitors. kubebuilder has a [plugin for controller Grafana dashboards](https://book.kubebuilder.io/plugins/grafana-v1-alpha) too, would that be useful to you? Just using controller metrics though, not cloudflared.

**Comment by pl4nty** [comment]
> It should already be possible to create your own cloudflared deployments, since the operator uses the Cloudflare API for routing, rather than a local config file. If that works for you, I can add a [GatewayInfrastructure](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.GatewayInfrastructure) parameter to disable the operator's deployments.

Would this approach work for you? I'd like to cut a release this week

**Comment by danielloader** [comment]
https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#manual-deployment

Would this count as a way to do manual deployments of gateways?

**Comment by pl4nty** [comment]
@danielloader not really, traffic flows directly to the tunnel so no services are involved. the operator matches gateway config to tunnels using `gateway.Name == tunnel.Name` instead.

**Comment by christensenjairus** [comment]
I would also like to see the replica count feature implemented so the gateway is highly available

**Comment by pl4nty** [comment]
v0.8.0 can [disable the built-in cloudflared Deployment](https://github.com/pl4nty/cloudflare-kubernetes-gateway#standalone-cloudflared) using a ConfigMap referenced by a Gateway. then you can deploy cloudflared separately and configure replicas, affinity, etc

**Comment by 0dragosh** [comment]
I wanted to do something similar and edit the cloudflared deployment. 

I like how elegant the cloudflare-kubernetes-gateway way is with regards to dns and tunnel lifecycle and didn't want to lose that by deploying and configuring my own, so I created a Kyverno policy that adds whatever you want to add to the `cloudflare` deployment:

```yaml
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: cloudflare-gateway-ha-config
spec:
  background: true
  rules:
    - name: set-replicas-and-topology
      match:
        any:
          - resources:
              kinds:
                - Deployment
              name: cloudflare-kubernetes-gateway
      mutate:
        patchesJson6902: |-
          - op: replace
            path: /spec/replicas
            value: 2
          - op: add
            path: /spec/template/spec/topologySpreadConstraints
            value:
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: cloudflare-kubernetes-gateway

```

Hope this is useful.
