### ISSUE TITLE
Add ready/healthcheck to cloudflared

### ISSUE THREAD

**Issue by pl4nty** [pl4nty/cloudflare-kubernetes-gateway#180]
https://github.com/cloudflare/argo-tunnel-examples/blob/master/named-tunnel-k8s/cloudflared.yaml

```yaml
livenessProbe:
  httpGet:
    # Cloudflared has a /ready endpoint which returns 200 if and only if
    # it has an active connection to the edge.
    path: /ready
    port: 2000
  failureThreshold: 1
  initialDelaySeconds: 10
  periodSeconds: 10
```
